spring:
  application:
    name: teligen-microservice-gateway-sample
server:
  port: 8050
logging:
  file: /tmp/${spring.application.name}.log
management:
  security:
    enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
zuul:
  ignored-services: teligen-microservice-provider-sample                        # 需要忽视的服务(配置后将不会被路由)
  routes:
    feign:                                                                      # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /feign/**                                                           # 想要映射到的路径
      service-id: teligen-microservice-consumer-sample                          # Eureka中的serviceId

#zuul:
#  add-proxy-headers: true
#  host:
#    connect-timeout-millis: 60000
#    socket-timeout-millis: 60000
#ribbon:
#  ConnectTimeout: 6000
#  ReadTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
 